
  services:
      bank:
        image: lowkent2me/bank:latest
        build: .
        ports:
            - 5000:5000
        restart: on-failure

      nginx:
        image: nginx:stable
        ports:
          - 80:80
        restart: on-failure
