
  services:
      bank:
        image: lowkent2me/bank:latest
        build:
          context: .
          dockerfile: ./Dockerfile
        ports:
            - 5000:5000
        restart: on-failure
        container_name: app-bank
        hostname: app-bank
        networks:
          app_net:
            ipv4_address: 172.16.1.5

      nginx:
        image: nginx:stable
        build:
          context: .
          dockerfile: ./Dockerfile_web
        ports:
          - 80:80
        depends_on:
          - bank
        restart: on-failure
        container_name: bank-nginx
        hostname: nginx-bank
        volumes:
            - ./nginx/logs:/var/log/nginx #logs.
            - ./nginx/conf.d/bank.conf:/etc/nginx/conf.d/bank.conf:ro #config app
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro #config nginx.
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro #sites.
            - ./nginx/crt:/etc/nginx/ssl:ro #certificates

      certbot:
        image: certbot/certbot
        depends_on:
          - nginx
        container_name: certbot
        volumes:
            - ./nginx/crt:/etc/letsencrypt #certificates
            - ./nginx/sites-enabled:/var/www/html
        command: certonly --webroot --webroot-path=/var/www/html --email vitalikot1996@gmail.com --agree-tos --no-eff-email -d kvs.bank.smodata.net

        networks:
            app_net:
              ipv4_address: 172.16.1.4

  networks:
    app_net:
      driver: bridge
      ipam:
        config:
          - subnet: 172.16.1.0/24