
  services:
      bank:
        image: lowkent2me/bank:latest
        build:
          context: .
          dockerfile: ./Dockerfile
        ports:
            - 5000:5000
        restart: on-failure
        container_name: app-nginx
        hostname: app-bank
        networks:
          app_net:
            ipv4_address: 172.16.1.5

      nginx:
        image: nginx:stable
        build:
          context: .
          dockerfile: ./Dockerfile_web
        ports:
          - 80:80
        depends_on:
          - bank
        restart: on-failure
        container_name: bank-nginx
        hostname: nginx-bank
        volumes:
            - /home/bank_kot/nginx/logs:/var/log/nginx #logs.
            - /home/bank_kot/nginx/nginx.conf:/etc/nginx/nginx.conf:ro #config nginx.
            - /home/bank_kot/nginx/sites-enabled:/etc/nginx/sites-enabled:ro #sites.
            - /home/bank_kot/nginx/crt:/etc/nginx/ssl:ro #certificates

        networks:
            app_net:
              ipv4_address: 172.16.1.4

  networks:
    app_net:
      driver: bridge
      ipam:
        config:
          - subnet: 172.16.1.0/24