apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bank.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.labels . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{ .Values.labels . | nindent 6 }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.maxSurge }}
  template:
    metadata:
      labels:
        {{ .Values.labels . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.deployment.template.spec.containers.nginx.name }}
          image: {{ .Values.deployment.template.spec.containers.nginx.image }}
          ports:
            - containerPort: {{ .Values.deployment.template.spec.containers.nginx.ports.containerPort }}
              name: {{ .Values.deployment.template.spec.containers.nginx.ports.name }}
              protocol: {{ .Values.deployment.template.spec.containers.nginx.ports.protocol }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
        - name: {{ include "test.fullname" . }}
          image: lowkent2me/bank:latest
      #        env:
      #        - name: PG_DATABASE
      #          value: bank
      #        - name: PG_USER
      #          valueFrom:
      #            secretKeyRef:
      #              key: username
      #              name: omega-db-creds
      #        - name: PG_PASSWORD
      #          valueFrom:
      #            secretKeyRef:
      #              key: password
      #              name: omega-db-creds
      #        - name: PG_HOST
      #          value: rds-omega-tf.c0whq4jiugzq.eu-north-1.rds.amazonaws.com
      #        - name: PG_PORT
      #          value: "5432"
      volumes:
        - configMap:
            name: bank-nginx-config
          name: nginx-config