apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omegabank-bank
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: omegabank
  source:
    repoURL: 'https://github.com/lowkent2me/dos14-Kot-git-flow.git'
    path: k8s/bank
    targetRevision: feature-CD
    helm:
      valueFiles:
        - /k8s/bank/values.yaml
      releaseName: omegabank-bank
  destination:
    namespace: omegabank
    name: dos14
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


#  sh '''
#sed -E 's/tag:.+$/tag: '"$GIT_COMMIT"'/g' k8s/bank/values.yaml
#  cat k8s/bank/values.yaml
#  git add .
#  git commit -m "Hello from Jenkins"
#  '''

