apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omegabank-bank
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: omegabank
  source:
    repoURL: 'https://github.com/lowkent2me/dos14-Kot-git-flow.git'
    path: k8s/bank
    targetRevision: feature-CD
    helm:
      valueFiles:
        - /k8s/bank/values.yaml
      releaseName: omegabank-bank
  destination:
    namespace: omegabank
    name: dos14
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

#  sh('git config --global user.email "vitalikot1996@gmail.com" && git config --global user.name "Jenkins"')
#  sh('git add .')
#sh('git commit -m "JENKINS: add image tag in helm chart tag for CD"')
#  sh('git remote set-url origin https://${SECRET}@github.com/lowkent2me/dos14-Kot-git-flow.git')
#  sh('git push origin feature-CD')