---
- name: installing my app
  hosts: all
  become: yes
  vars:

  tasks:
    - name: create user bank
      user:
        name: bank
        group: sudo
        state: present
        password: "{{ 'bank' |  password_hash('sha512', 'withsomesalt') }}"
        shell: /bin/bash

    - name: install git
      apt:
        name: git
        state: latest
        update_cache: yes

    - name: add repository for latest python
      shell: add-apt-repository ppa:deadsnakes/ppa -y

    - name: install python v3.11
      apt:
        name: python3.11
        state: latest

    - name: install pip
      apt: name=python3-pip state=latest

    - name: install poetry from pip
      shell: pip install poetry

    - name: create directory for repo
      file:
        path: /home/bank/project
        state: directory

    - name: add ssh directory
      file:
        path: /home/bank/.ssh
        state: directory

    - name: add key to user bank
      copy:
        src: keys/keys
        dest: /home/bank/.ssh/
        mode: 0400

    - name: clone repo
      git:
        repo: git@github.com:lowkent2me/dos14-Kot-git-flow.git
        key_file: /home/bank/.ssh/keys
        dest: /home/bank/project
        version: master
        single_branch: true
        accept_hostkey: yes

    - name: install dependencies
      shell: |
        poetry install
        poetry update --with dev
      args:
        chdir: /home/bank/project

    - name: add systemd ini-file
      copy:
        src: unit/banktms.service
        dest: /etc/systemd/system/
      tags: copys

    - name: start banktms service
      systemd:
        name: banktms
        state: started
      environment:
        XDG_RUNTIME_DIR: "/etc/systemd/system/"
      tags: last