---
- name: prepare server for my app
  hosts: all
  become: yes
  vars:

  pre_tasks:
    - name: create user bank
      user:
        name: bank_kot
        group: sudo
        state: present
        password: "{{ 'bank' |  password_hash('sha512', 'withsomesalt') }}"
        shell: /bin/bash

    - name: install git
      apt:
        name: git
        state: latest
        update_cache: yes

    - name: create directory for repo
      file:
        path: /home/bank_kot/project
        state: directory

    - name: add ssh directory
      file:
        path: /home/bank_kot/.ssh
        state: directory

    - name: add key to user bank
      copy:
        src: keys/keys
        dest: /home/bank_kot/.ssh/
        mode: 0400

    - name: clone repo
      git:
        repo: git@github.com:lowkent2me/dos14-Kot-git-flow.git
        key_file: /home/bank_kot/.ssh/keys
        dest: /home/bank_kot/project
        version: "{{ BRANCH }}"
        force: yes
        accept_hostkey: yes

  roles:
    - install_docker_engine

  tasks:
    - name: add systemd ini-file
      copy:
        src: unit/banktms.service
        dest: /etc/systemd/system/

    - name: Create directories for nginx
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /home/bank_kot/nginx
        - /home/bank_kot/nginx/conf.d
        - /home/bank_kot/nginx/logs
        - /home/bank_kot/nginx/crt
        - /home/bank_kot/nginx/sites_enabled

    - name: copy nginx.conf
      copy:
        src: /home/bank/project/nginx_config/nginx.conf
        dest: /home/bank_kot/nginx/

    - name: copy bank.conf
      copy:
        src: /home/bank/project/nginx_config/bank.conf
        dest: /home/bank_kot/nginx/conf.d/

    - name: start banktms service
      systemd:
        name: banktms
        state: started
        daemon-reload: true
