---
- name: installing my app
  hosts: all
  become: yes
  vars:

  tasks:
    - name: create user bank
      user:
        name: bank
        group: sudo
        state: present
        password: "{{ 'bank' |  password_hash('sha512', 'withsomesalt') }}"
        shell: /bin/bash

    - name: install git
      apt:
        name: git
        state: latest
        update_cache: yes

    - name: install python v3.11
      apt:
        name: python3.11
        state: latest
      shell: sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
             sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 2

