---
# tasks file for install_docker_engine

- name: removing old docker engine
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: install packages for https repo
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - ca-certificates
    - curl
    - gnupg

- name: add gpg keys
  shell: |
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

- name: add docker repo
  shell: |
    echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: install docker
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
